const ACTIONS ={
    NOTIFY:'NOTIFY',
    AUTH:'AUTH',
    VOTEPOWER:'VOTEPOWER',
    VOTEWEİGTH:'VOTEWEİGTH',
    STEEMDLR:'STEEMDLR',
    SBDDLR:'SBDDLR',
    BUSDDLR:'BUSDDLR'


    
}

export default ACTIONS